### ISSUE TITLE
java.lang.UnsatisfiedLinkError: tinyb.BluetoothManager.getNativeAPIVersion()Ljava/lang/String;

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/tinyb#1]
Encountered the following error while writing a simple demo using tinyb in Java (tinyb-example-plain, commit df082bfc54d371509ef3215ffaab721cce7e48a2):

```sh
tinyb-example-plain# java -cp ../tinyb/build/java/tinyb.jar:tinyb-example-plain.jar de.interoberlin.HelloTinyB DB:45:1A:E7:BB:C0
Native code library failed to load.
java.lang.UnsatisfiedLinkError: /usr/lib/x86_64-linux-gnu/libjavatinyb.so.0.5.0-8-g6e580f4.0.5.0-8-g6e580f4.0.5.0-8-g6e580f4: libjawt.so: cannot open shared object file: No such file or directory
Exception in thread "main" java.lang.UnsatisfiedLinkError: tinyb.BluetoothManager.getNativeAPIVersion()Ljava/lang/String;
        at tinyb.BluetoothManager.getNativeAPIVersion(Native Method)
        at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:304)
        at de.interoberlin.HelloTinyB.main(HelloTinyB.java:111)
```

**Comment by matthiasbock** [comment]
```sh
apt install openjdk-8-jdk
```
installed
* openjdk-8-jdk,
* openjdk-8-jdk-headless,
* openjdk-8-jre and
* openjdk-8-jre-headless

Java Debian packages with version 8u144-b01-1.
Error persists, although libjawt.so is present under /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/.

**Comment by matthiasbock** [comment]
See also: https://github.com/intel-iot-devkit/tinyb/issues/63

Problem is resolved by adding the following lines to the ~/.bashrc:
```bash
export JAVA_HOME=$(readlink -f $(which java) | sed "s:/jre/bin/java::")
export PATH=${PATH}:${JAVA_HOME}/bin
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${JAVA_HOME}/lib/amd64:${JAVA_HOME}/jre/lib/amd64"
```
