### ISSUE TITLE
java.lang.RuntimeException: Native library is out of date. Please update the native library.

### ISSUE THREAD

**Issue by matthiasbock** [interoberlin/tinyb#2]
Encountered the following error while writing a simple demo using tinyb in Java (project tinyb-example-plain, commit df082bfc54d371509ef3215ffaab721cce7e48a2):

```sh
tinyb-example-plain# java -cp ../tinyb/build/java/tinyb.jar:tinyb-example-plain.jar de.interoberlin.HelloTinyB DB:45:1A:E7:BB:C0
Exception in thread "main" java.lang.RuntimeException: Native library is out of date. Please update the native library.
        at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:317)
        at de.interoberlin.HelloTinyB.main(HelloTinyB.java:111)

```

**Comment by matthiasbock** [comment]
The tinyb jar and libraries had to be rebuilt:
```sh
find /usr -maxdepth 4 -name "*tinyb*" -exec rm {} \;
cd tinyb/build/
make clean all install
```

The demo now works:
```sh
tinyb-example-plain# java -cp ../tinyb/build/java/tinyb.jar:tinyb-example-plain.jar de.interoberlin.HelloTinyB DB:45:1A:E7:BB:C0
The discovery started: true
Discovery could not be stopped.
Found device: Address = DB:45:1A:E7:BB:C0 Name = WunderbarHTU Connected = false
Sensor with the provided address connected
Services exposed by device:
UUID: 0000180f-0000-1000-8000-00805f9b34fb
UUID: 00002002-0000-1000-8000-00805f9b34fb
UUID: 00001801-0000-1000-8000-00805f9b34fb
UUID: 0000180a-0000-1000-8000-00805f9b34fb
```
